### ISSUE TITLE
It works, but QoL issues

### ISSUE THREAD

**Issue by 58sekkonds** [Aminoa/auto-daily-screener#1]
It works! With caveats. 

I have to log into Brightspace using my phone and other devices. The script is useful, but having to click on a few extra buttons to log in (daily) from other devices is not very efficient. I have it set so that it automatically sends a Duo notif to my phone, and with this script enabled, I wouldn't have that feature anymore. Kind of the opposite of what you're trying to achieve. 

I'm not a comp sci major, but I personally don't think it should be that hard to fix it. Just made it so that it can click on the Auto Daily Screener instead. Maybe I'm just wrong and dumb, though. 

Good job on your work so far. I was planning on asking a few comp sci friends on how to automate just this, and I guess you got 90% of the way there already.

**Comment by aminoa** [comment]
That could be relatively simple to implement but I would need to determine which device is the ADS (which is possible but it would require the user to rename the device to a specific title. Tbh, I'm not sure when I'll continue work on this (at least for now) but I'll reply to this thread if I plan on adding this feature.
